# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# 
import collections

TestCase = collections.namedtuple('TestCase', "description input_table_name input_commit_statement input_primary_key_fields expected_sql")

tests=[
  TestCase(
    description="Simple",
    input_table_name="TT_DETN_EVNT", 
    input_commit_statement="""delete from "DEDB"."TT_DETN_EVNT" where "AUTOGENERATED" = '0'""", 
    input_primary_key_fields = "AUTOGENERATED",
    expected_sql="DELETE FROM TT_DETN_EVNT WHERE AUTOGENERATED = '0'")

, TestCase(
    description="Trailing spaces at the end of redo statement",
    input_table_name="TT_DETN_EVNT", 
    input_commit_statement="""delete from "DEDB"."TT_DETN_EVNT" where "AUTOGENERATED" = '0'       """, 
    input_primary_key_fields = "AUTOGENERATED",
    expected_sql="DELETE FROM TT_DETN_EVNT WHERE AUTOGENERATED = '0'")

, TestCase(
    description="Single quote inside value",
    input_table_name="TT_DETN_EVNT", 
    input_commit_statement="""delete from "DEDB"."TT_DETN_EVNT" where "AUTOGENERATED" = ''''""", 
    input_primary_key_fields = "AUTOGENERATED",
    expected_sql="DELETE FROM TT_DETN_EVNT WHERE AUTOGENERATED = ''''")

, TestCase(
    description="Single quote starting, followed by comma",
    input_table_name="TT_DETN_EVNT", 
    input_commit_statement="""delete from "DEDB"."TT_DETN_EVNT" where "AUTOGENERATED" = ''','""", 
    input_primary_key_fields = "AUTOGENERATED",
    expected_sql="DELETE FROM TT_DETN_EVNT WHERE AUTOGENERATED = ''','")

, TestCase(
    description="Single quote following char, followed by comma",
    input_table_name="TT_DETN_EVNT", 
    input_commit_statement="""delete from "DEDB"."TT_DETN_EVNT" where "AUTOGENERATED" = '0'','""", 
    input_primary_key_fields = "AUTOGENERATED",
    expected_sql="DELETE FROM TT_DETN_EVNT WHERE AUTOGENERATED = '0'','")

, TestCase(
    description="Function should be stripped",
    input_table_name="TT_DETN_EVNT", 
    input_commit_statement="""delete from "DEDB"."TT_DETN_EVNT" where "AUTOGENERATED" = TO_TIMESTAMP('0')""", 
    input_primary_key_fields = "AUTOGENERATED",
    expected_sql="DELETE FROM TT_DETN_EVNT WHERE AUTOGENERATED = '0'")

, TestCase(
    description="Function string within quotes should not be stripped",
    input_table_name="TT_DETN_EVNT", 
    input_commit_statement="""delete from "DEDB"."TT_DETN_EVNT" where "AUTOGENERATED" = 'TO_TIMESTAMP(0)'""", 
    input_primary_key_fields = "AUTOGENERATED",
    expected_sql="DELETE FROM TT_DETN_EVNT WHERE AUTOGENERATED = 'TO_TIMESTAMP(0)'")

, TestCase(
    description="Function outside quotes should be stripped and function string within quotes should not be stripped",
    input_table_name="TT_DETN_EVNT", 
    input_commit_statement="""delete from "DEDB"."TT_DETN_EVNT" where "AUTOGENERATED" = TO_TIMESTAMP('TO_TIMESTAMP(0)')""", 
    input_primary_key_fields = "AUTOGENERATED",
    expected_sql="DELETE FROM TT_DETN_EVNT WHERE AUTOGENERATED = 'TO_TIMESTAMP(0)'")

, TestCase(
    description="WHERE clause ending with IS NULL",
    input_table_name="TT_DETN_EVNT", 
    input_commit_statement="""delete from "DEDB"."TT_DETN_EVNT" where "AUTOGENERATED" = '0' and "ESCALATIONDATE" IS NULL""", 
    input_primary_key_fields = "AUTOGENERATED",
    expected_sql="DELETE FROM TT_DETN_EVNT WHERE AUTOGENERATED = '0'")

, TestCase(
    description="WHERE clause beginning with IS NULL",
    input_table_name="TT_DETN_EVNT", 
    input_commit_statement="""delete from "DEDB"."TT_DETN_EVNT" where "ESCALATIONDATE" IS NULL and "AUTOGENERATED" = '0'""", 
    input_primary_key_fields = "AUTOGENERATED",
    expected_sql="DELETE FROM TT_DETN_EVNT WHERE AUTOGENERATED = '0'")

, TestCase(
    description="WHERE clause with IS NULL primary key should still use the full WHERE clause",
    input_table_name="TT_DETN_EVNT", 
    input_commit_statement="""delete from "DEDB"."TT_DETN_EVNT" where "ESCALATIONDATE" IS NULL and "AUTOGENERATED" = '0'""", 
    input_primary_key_fields = "AUTOGENERATED, ESCALATIONDATE",
    expected_sql="DELETE FROM TT_DETN_EVNT WHERE AUTOGENERATED = '0' AND ESCALATIONDATE IS NULL")

, TestCase(
    description="where keyword in where clause",
    input_table_name="TT_DETN_EVNT", 
    input_commit_statement="""delete from "DEDB"."TT_DETN_EVNT" where "AUTOGENERATED" = ' where '""", 
    input_primary_key_fields = "AUTOGENERATED",
    expected_sql="DELETE FROM TT_DETN_EVNT WHERE AUTOGENERATED = ' where '")

, TestCase(
    description="where keyword with single and double quote in where clause",
    input_table_name="TT_DETN_EVNT", 
    input_commit_statement="""delete from "DEDB"."TT_DETN_EVNT" where "AUTOGENERATED" = ''' where "'""", 
    input_primary_key_fields = "AUTOGENERATED",
    expected_sql="""DELETE FROM TT_DETN_EVNT WHERE AUTOGENERATED = ''' where "'""")

, TestCase(
    description="String with everything put together",
    input_table_name="TT_DETN_EVNT", 
    input_commit_statement="""delete from "DEDB"."TT_DETN_EVNT" where "ESCALATIONDATE" IS NULL and "AUTOGENERATED" = '0' and "FIELD0" IS NULL and "FIELD1" = 'Something'', ''WITH_A_FUNCTION_LOOKALIKE(''something'')' and "FIELD2" = TO_TIMESTAMP('timestamp') and "FIELD3" = ANOTHER_FUNCTION('another function #value","')""", 
    input_primary_key_fields = "FIELD3, FIELD1, FIELD2",
    expected_sql='DELETE FROM TT_DETN_EVNT WHERE FIELD2 = \'timestamp\' AND FIELD3 = \'another function #value","\' AND FIELD1 = \'Something\'\', \'\'WITH_A_FUNCTION_LOOKALIKE(\'\'something\'\')\'')

, TestCase(
    description="Real-world LogMiner redo statement example",
    input_table_name="TT_DETN_EVNT", 
    input_commit_statement="""delete from "DEDB"."TT_DETN_EVNT" where "DETN_EVNT_ID" = '20160918161906411' and "USG_REC_ID" = '20160918161906411' and "DETN_EVNT_NO" = '0112160918001934' and "LANE_ID" = '11229994752' and "LANE_CODE" = '01' and "DETN_PNT_CODE" = '2B' and "OPER_CODE" = '112' and "PRI_TAG_ID" = '44364161906412' and "EVNT_TYPE" = 'LF' and "EVNT_STAT" = '901' and "IDTN_METH" = 'TAG' and "IDTN_RECD" IS NULL and "LPN" IS NULL and "PLT_ISSR" IS NULL and "FINAL_VEH_CLS" = '2' and "LPN_DETER_CODE" IS NULL and "OCR_CONF" IS NULL and "PASS_REF_NUM" IS NULL and "RDSD_EVNT_NUM" IS NULL and "RDSD_CLS" = '2' and "RDSD_CLS_CONF" IS NULL and "GUID" IS NULL and "QUALIFIER" IS NULL and "GLB_STATE" IS NULL and "TMU_STATE" IS NULL and "VIS_STATE" IS NULL and "DSRC_STATE" IS NULL and "DRAWBAR_PRESN" IS NULL and "DETN_PNT_STAT" IS NULL and "VDR_NUM" IS NULL and "VEH_SPEED" IS NULL and "VEH_HEIGHT" IS NULL and "VEH_AXLE_CLS" IS NULL and "VEH_LANE" IS NULL and "REG_PLT_TYPE" IS NULL and "REG_VEH_CLS" IS NULL and "PURPOSE_OF_USE" IS NULL and "ACCT_NUM" = '626888920001' and "ACCT_TYPE" = 'FULL' and "ACCT_STAT" = 'X' and "CUST_NUM" = '0062688892' and "ISSR_CODE" = '201' and "FORGN_ACCT_TYPE" IS NULL and "FORGN_ACCT_NUM" IS NULL and "FORGN_ACCT_ISSR" IS NULL and "FLEET_REF_NUM" IS NULL and "VIDEO_EXEMPT_FLAG" IS NULL and "FLOW_FLAG" = '0' and "DETN_TIME" = TO_TIMESTAMP('18-SEP-2016 02:39:28.0 AM') and "CRET_TIME" = TO_TIMESTAMP('23-OCT-2016 01:04:03.3270000 AM') and "LAST_UPD" = TO_TIMESTAMP('23-OCT-2016 01:04:03.0 AM') and "VEH_LOOKUP_CLS" IS NULL and "FORGN_TFR_TYPE" IS NULL and "FORGN_TFR_NAME" IS NULL and "FORGN_TFR_CONT_METH" IS NULL and "FORGN_TFR_CONT_DTL" IS NULL and "SWEEPABLE" IS NULL""", 
    input_primary_key_fields = "DETN_EVNT_ID, DETN_EVNT_NO, LANE_ID",
    expected_sql="DELETE FROM TT_DETN_EVNT WHERE LANE_ID = '11229994752' AND DETN_EVNT_NO = '0112160918001934' AND DETN_EVNT_ID = '20160918161906411'")


]
