# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# 
import pytest
from data_pipeline.sql.where_statement import WhereStatement
from data_pipeline.processor.oracle_where_parser import OracleWhereParser

@pytest.mark.parametrize("commit_statement, primary_key_fields, where_beg_i, expected_conditions", [
    ("""where "AUTOGENERATED" = '0'""",["AUTOGENERATED"], 0, " WHERE AUTOGENERATED = '0'"),
    ("""update "MY_SCHEMA"."MY_TABLE_3" set "FIELD0" = '3' where "AUTOGENERATED" = '0'""", ["AUTOGENERATED"], 49, " WHERE AUTOGENERATED = '0'"),
    ("""update "MY_SCHEMA"."MY_TABLE_3" set "FIELD0" = '3 where ' where "AUTOGENERATED" = '0'""", ["AUTOGENERATED"], 56, " WHERE AUTOGENERATED = '0'"),
    ("""update "MY_SCHEMA"."MY_TABLE_3" set "FIELD0" = '3 where ' where "AUTOGENERATED" = '0' and "FIELD0" = 'something where '""", ["AUTOGENERATED", "FIELD0"], 56, " WHERE AUTOGENERATED = '0' AND FIELD0 = 'something where '"),
    ("""update "MY_SCHEMA"."MY_TABLE_3" set "FIELD0" = '3 '' where "' where "AUTOGENERATED" = '0' and "FIELD0" = 'something where '""", ["AUTOGENERATED"], 60, " WHERE AUTOGENERATED = '0'"),
    ])
def test_where_parse(commit_statement, primary_key_fields, where_beg_i, expected_conditions):
    where_statement = WhereStatement("MY_SCHEMA", None, primary_key_fields)
    parser = OracleWhereParser()
    parser.set_commit_statement(commit_statement)
    parser.set_read_cursor(where_beg_i)
    parser.set_statement(where_statement)
    parser.set_primary_keys(primary_key_fields)
    parser.parse()
    assert str(where_statement) == expected_conditions


